<?php

function hj_places_get_marker_types() {
    $marker_types = array(
        "default" => elgg_echo("hj:maps:markertype:default"),
        "airport" => elgg_echo("hj:maps:markertype:airport"),
        "amusement_park" => elgg_echo("hj:maps:markertype:amusement_park"),
        "aquarium" => elgg_echo("hj:maps:markertype:aquarium"),
        "art_gallery" => elgg_echo("hj:maps:markertype:art_gallery"),
        "atm" => elgg_echo("hj:maps:markertype:atm"),
        "bakery" => elgg_echo("hj:maps:markertype:bakery"),
        "bank" => elgg_echo("hj:maps:markertype:bank"),
        "bar" => elgg_echo("hj:maps:markertype:bar"),
        "beauty_salon" => elgg_echo("hj:maps:markertype:beauty_salon"),
        "bicycle_store" => elgg_echo("hj:maps:markertype:bicycle_store"),
        "bowling_alley" => elgg_echo("hj:maps:markertype:bowling_alley"),
        "bus_station" => elgg_echo("hj:maps:markertype:bus_station"),
        "cafe" => elgg_echo("hj:maps:markertype:cafe"),
        "campground" => elgg_echo("hj:maps:markertype:campground"),
        "car_dealer" => elgg_echo("hj:maps:markertype:car_dealer"),
        "car_rental" => elgg_echo("hj:maps:markertype:car_rental"),
        "car_repair" => elgg_echo("hj:maps:markertype:car_repair"),
        "car_wash" => elgg_echo("hj:maps:markertype:car_wash"),
        "casino" => elgg_echo("hj:maps:markertype:casino"),
        "cemetery" => elgg_echo("hj:maps:markertype:cemetery"),
        "church" => elgg_echo("hj:maps:markertype:church"),
        "city_hall" => elgg_echo("hj:maps:markertype:city_hall"),
        "clothing_store" => elgg_echo("hj:maps:markertype:clothing_store"),
        "convenience_store" => elgg_echo("hj:maps:markertype:convenience_store"),
        "courthouse" => elgg_echo("hj:maps:markertype:courthouse"),
        "dentist" => elgg_echo("hj:maps:markertype:dentist"),
        "department_store" => elgg_echo("hj:maps:markertype:department_store"),
        "electrician" => elgg_echo("hj:maps:markertype:electrician"),
        "electronics_store" => elgg_echo("hj:maps:markertype:electronics_store"),
        "embassy" => elgg_echo("hj:maps:markertype:embassy"),
        "finance" => elgg_echo("hj:maps:markertype:finance"),
        "fire_station" => elgg_echo("hj:maps:markertype:fire_station"),
        "florist" => elgg_echo("hj:maps:markertype:florist"),
        "food" => elgg_echo("hj:maps:markertype:food"),
        "furniture_store" => elgg_echo("hj:maps:markertype:furniture_store"),
        "gas_station" => elgg_echo("hj:maps:markertype:gas_station"),
        "government_office" => elgg_echo("hj:maps:markertype:government_office"),
        "gym" => elgg_echo("hj:maps:markertype:gym"),
        "hardware_store" => elgg_echo("hj:maps:markertype:hardware_store"),
        "hospital" => elgg_echo("hj:maps:markertype:hospital"),
        "jewelry_store" => elgg_echo("hj:maps:markertype:jewelry_store"),
        "laundry" => elgg_echo("hj:maps:markertype:laundry"),
        "lawyer" => elgg_echo("hj:maps:markertype:lawyer"),
        "library" => elgg_echo("hj:maps:markertype:library"),
        "liquor_store" => elgg_echo("hj:maps:markertype:liquor_store"),
        "lodging" => elgg_echo("hj:maps:markertype:lodging"),
        "mosque" => elgg_echo("hj:maps:markertype:mosque"),
        "movie_rental" => elgg_echo("hj:maps:markertype:movie_rental"),
        "movie_theater" => elgg_echo("hj:maps:markertype:movie_theater"),
        "museum" => elgg_echo("hj:maps:markertype:museum"),
        "night_club" => elgg_echo("hj:maps:markertype:night_club"),
        "park" => elgg_echo("hj:maps:markertype:park"),
        "parking" => elgg_echo("hj:maps:markertype:parking"),
        "pharmacy" => elgg_echo("hj:maps:markertype:pharmacy"),
        "police" => elgg_echo("hj:maps:markertype:police"),
        "post_office" => elgg_echo("hj:maps:markertype:post_office"),
        "restaurant" => elgg_echo("hj:maps:markertype:restaurant"),
        "school" => elgg_echo("hj:maps:markertype:school"),
        "shoe_store" => elgg_echo("hj:maps:markertype:shoe_store"),
        "shopping_mall" => elgg_echo("hj:maps:markertype:shopping_mall"),
        "spa" => elgg_echo("hj:maps:markertype:spa"),
        "stadium" => elgg_echo("hj:maps:markertype:stadium"),
        "store" => elgg_echo("hj:maps:markertype:store"),
        "subway_station" => elgg_echo("hj:maps:markertype:subway_station"),
        "synagogue" => elgg_echo("hj:maps:markertype:synagogue"),
        "taxi_stand" => elgg_echo("hj:maps:markertype:taxi_stand"),
        "train_station" => elgg_echo("hj:maps:markertype:train_station"),
        "university" => elgg_echo("hj:maps:markertype:university"),
        "veterinary_care" => elgg_echo("hj:maps:markertype:veterinary_care"),
        "zoo" => elgg_echo("hj:maps:markertype:zoo")
    );
    
    $marker_types = elgg_trigger_plugin_hook('hj:maps:markertypes', 'all', $marker_types, $marker_types);
    
    return $marker_types;
}
